[package]
name = "wasm"
version = "0.1.0"
authors = ["mtwtkman <punipuniomochi@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
runtime = { path = "../runtime" }
wee_alloc = "0.4"